### ISSUE TITLE
Error message after updating Category and Product Set of a product

### ISSUE THREAD

**Issue by ChristianAF** [saucal/facebook-for-woocommerce#10]
[![Screenshot_2021-01-27_15-47-32.png](https://mrkr.io/s/60118b14e73f7a0ee6ee4f2b/2)](https://mrkr.io/s/60118b14e73f7a0ee6ee4f2b/0)

https://user-images.githubusercontent.com/43881685/106017865-b785d500-609f-11eb-86aa-07af20a35b42.mp4

The Product Set "Duplicate" was with only one product. I just edit the product by unselecting "Duplicate" on PRodcut set.

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://testsite.saucal.com/wp-admin/post.php?post=39&action=edit](https://testsite.saucal.com/wp-admin/post.php?post=39&action=edit)

<table><tr><td><strong>Browser</strong></td><td>Chrome 87.0.4280.141</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Linux</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 637</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by sc-ecolasurdo** [comment]
Can you check now @ChristianAF please?
