### ISSUE TITLE
Product Set taxonomy list: show the correct number of “posts” (products) or remove count column from list.

### ISSUE THREAD

**Issue by ChristianAF** [saucal/facebook-for-woocommerce#5]
[![Screenshot_2020-11-25_18-44-12.png](https://mrkr.io/s/5fbea5fc388a1f568b22559b/2)](https://mrkr.io/s/5fbea5fc388a1f568b22559b/0)

Count column is no correct

---

**Reported by:** Christian Fricker (christian@saucal.com)
**Source URL:** [https://testsite.saucal.com/wp-admin/edit-tags.php?taxonomy=fb_product_set&post_type=product](https://testsite.saucal.com/wp-admin/edit-tags.php?taxonomy=fb_product_set&post_type=product)
<table><tr><td><strong>Browser</strong></td><td>Chrome 87.0.4280.66</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Linux</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 637</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by sc-ecolasurdo** [comment]
@ChristianAF This is ready to test.
